% Script for exporting special measure data file
% to .csv file with headers 

max_run_number = 69;
path = '/Volumes/GoogleDrive-107994170655487708077/Shared drives/JDSY Lab/Data/Squeezing Project Data/20240913 S51 Dil_Hamster/CSV Export From Matlab';
sm_datafolder = '/Raw_S51_Hamster_Dil_Data/';

% check if save folder exists
if ~exist(append(path, "/CSV_header_data"), 'dir')
    mkdir(append(path, "/CSV_header_data"))
end


for index = 1:max_run_number
    % check if file is present assuming file name convention
    % is "squeezing_runnumber" 

    % pad integers with leading zeros 
    run_number = sprintf('%03d', index); 
    file_path = append(path, sm_datafolder, "squeezing_", run_number, ".mat");

    % check if file exists
    if isfile(file_path)
        % if exists, then first import data into workspace
        disp(string(index)); 
        importfile(file_path);

        % correct data
        % noticed that sometimes the column length isn't always the same 
        % only present in aborted runs 
        % add filler nans to make square
        
        column_length = 0; 
        for index2 = 1:length(data)
            if length(data{1,index2}) > column_length
                column_length = length(data{1,index2});
            end 
        end 

        for index3 = 1:length(data)
            data{1, index3}(end+1:column_length,1) = missing; 
        end 

        % then export 
        save_path = append(path, "/CSV_header_data_test/");
        csvwrite(append(save_path, "Run", string(index), "_data.csv"), data);
        writecell(scan.loops.getchan, append(save_path, "Run", string(index), "_header.csv"));
    end 
end 





function importfile(fileToRead1)
%IMPORTFILE(FILETOREAD1)
%  Imports data from the specified file
%  FILETOREAD1:  file to read

%  Auto-generated by MATLAB on 28-Sep-2024 06:31:52

% Import the file
newData1 = load('-mat', fileToRead1);

% Create new variables in the base workspace from those fields.
vars = fieldnames(newData1);
for i = 1:length(vars)
    assignin('base', vars{i}, newData1.(vars{i}));
end
end 
